.\" Hey, EMACS: -*- nroff -*-
.\" Copyright (C) 2015 Sergio Durigan Junior <sergiodj@sergiodj.net>
.\"
.\" This document is free software.  You may distribute and/or modify
.\" it under the terms of:
.\"
.\" * The GNU General Public License, as published by the Free
.\"   Software Foundation, version 3 or (at your option) any later
.\"   version.  You should have received a copy of the GNU General
.\"   Public License along with this program.  If not, see
.\"   <http://www.gnu.org/licenses/>.
.\"
.\" $Id$
.TH SLEEPYHEAD 1 "version 1.0.0" "July 2016"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME

SleepyHead \- Sleep tracking software with a focus on monitoring CPAP treatment.

.SH DESCRIPTION

\fBSleepyHead\fP is a Free Software, cross platform research tool for
exploring data produced by CPAP (Continuous Positive Airway Pressure)
machines, and related equipment, which are used in the treatment of
sleep apnea and other sleep disorders.

\fBSleepyHead\fP supports data capable CPAP machine models from the
following series:

 - ResMed S9
 - AirSense 10
 - AirCurve 10
 - Philips Respironics System One
 - Fisher & Paykel ICON & ICON+
 - DeVilbiss IntelliPAP

The software supports the full range of Contec CMS50 series of
Oximeters, either standalone or synced with CPAP data (although you
will need to install a separate driver for Contact equipments).  It
also supports ResMed and PR System One oximeter attachments and file
imports from ChoiceMMed MD300W1 oximeters.

.SH OPTIONS

This program does not accept command-line options.

.SH BUGS

\fB<https://bugs.jedimark.net>\fP.

.SH HOMEPAGE

\fB<http://sleepyhead.sourceforge.net>\fP

.SH AUTHORS

Mark Watkins  <jedimark@users.sourceforge.net>

.PP

This manual page was written by Sergio Durigan Junior <sergiodj@sergiodj.net>.
